### ISSUE TITLE
Изменение статуса тайтла

### ISSUE THREAD

**Issue by TristisOris** [qt-kaneko/Shikiplayer#10]
Иногда, воспроизводится не каждый раз, плеер возвращает просмотренные сериалы в статус "Смотрю", и более того сбрасывает счетчик эпизодов.
Например здесь я просто полистал озвучку в одной из серий.
![image](https://github.com/qt-kaneko/Shikiplayer/assets/1270117/6e7b3c97-704f-4a8b-8715-cb1821eec56e)

Отметил просмотреным, опять запустил первую серию, сразу поставил на паузу - статус изменился, эпизоды сбросились на 0.
![image](https://github.com/qt-kaneko/Shikiplayer/assets/1270117/f704cffa-881a-4889-aa9f-e6f94a8e1eb4)
![image](https://github.com/qt-kaneko/Shikiplayer/assets/1270117/1d3188ca-7b07-4bb7-b377-7cdd6100b1c5)

Тоже самое с брошенным, но так же не всегда. В одном сериале отсмотрел серий 5, они отметились, а статус брошено так и остался.
Если отдельная серия отмечается гдето после 80% эпизода, то перевод в "смотрю" практически сразу.
Аналогично при просмотре последней серии иногда статус меняется на "Просмотрено", а иногда на "смотрю 26\26".

В идеале хотелось бы иметь возможность отключить любое вмешательство в карточку тайтла, тк запускать плеер я могу по любой причине, а пытаться вспомнить почему условный Гандам не посмотрен и висит в онгоинге это сложно.

**Comment by qt-kaneko** [comment]
> Иногда, воспроизводится не каждый раз

1. Это вопросы к Kodik'у, мы его не разрабатываем.

> плеер возвращает просмотренные сериалы в статус "Смотрю", и более того сбрасывает счетчик эпизодов

2. Shikiplayer сохраняет просматриваемую серию при паузе, а так же сохраняет серию как просмотренную если время до конца эпизода < 3 минут.
Теперь не будет ничего менять если аниме уже просмотрено (в следующем обновлении).

> Тоже самое с брошенным, но так же не всегда. В одном сериале отсмотрел серий 5, они отметились, а статус брошено так и остался.

> Если отдельная серия отмечается гдето после 80% эпизода, то перевод в "смотрю" практически сразу.

3. Без понятия, посмотрим позже, сейчас Kodik наелся и спит. Вы перезагружали страницу?

> Аналогично при просмотре последней серии иногда статус меняется на "Просмотрено", а иногда на "смотрю 26\26".

4. Управлением статусом Смотрю/Просмотрено занимается Shikimori, Shikiplayer просто указывает что эпизод просмотрен. Если хотите, можем сделать своё управление статусом Смотрю/Просмотрено.

> В идеале хотелось бы иметь возможность отключить любое вмешательство в карточку тайтла, тк запускать плеер я могу по любой причине, а пытаться вспомнить почему условный Гандам не посмотрен и висит в онгоинге это сложно.

5. Меню настроек Shikiplayer'а в данный момент нет и добавлять особого желания тоже нет, надеюсь вам подойдёт решение в пункте [2].

**Comment by TristisOris** [comment]
> Вы перезагружали страницу?

> Если хотите, можем сделать своё управление статусом Смотрю/Просмотрено.

Мне лично функционала сайта с головой достаточно.
Я тут больше не про удобно\неудобно, а то что в одинаковых условиях получается разный результат. Со временем приучился обновлять страницу прежде чем закрыть ее или начать ставить оценки.

Если статусы перестанут произвольно меняться, то это решит все основные проблемы. Спасибо.

**Comment by qt-kaneko** [comment]
> Мне лично функционала сайта с головой достаточно.

99% вам очень быстро надоест менять просмотренную серию)

> Со временем приучился обновлять страницу прежде чем закрыть ее

Вам не нужно обновлять страницу чтобы сохранить изменения, они и так сохранены, просто информация на странице тайтла устарела, это то же самое что открыть 2 вкладки и поменять на 1 из них статус тайтла.

**Comment by TristisOris** [comment]
> 99% вам очень быстро надоест менять просмотренную серию)
а я их не менял никогда) смотрю залпом, отмечаю все сразу.

> Вам не нужно обновлять страницу
чтобы убедиться, что все корректно заполнилось.
