### ISSUE TITLE
shiki log

### ISSUE THREAD

**Issue by deltaradune** [qt-kaneko/Shikiplayer#11]
Можете скрыть логи данного расширения?
![image](https://github.com/qt-kaneko/Shikiplayer/assets/84010434/ac6d5cb7-8706-4d49-bbd8-a91061bfb0ee)
![image](https://github.com/qt-kaneko/Shikiplayer/assets/84010434/a70bbec7-a6d2-4618-88d4-bd31e2a08286)

**Comment by qt-kaneko** [comment]
Это не логи, а информация о просматриваемом времени и выбранной озвучке, чтобы вам не приходилось каждый раз выбирать озвучку по возвращению к аниме, а так же мотать на нужное время, если вы не досмотрели.
На данный момент эта функция не выключаема, если хотите - можем сделать чтобы её можно было отключить.
