### ISSUE TITLE
Отсутствуют некоторые озвучки

### ISSUE THREAD

**Issue by Lenni-s** [qt-kaneko/Shikiplayer#12]
В списке озвучек которые предоставляет плеер на Шикимори, отсутсвуют отзвучки "Студийной Банды". Хотя на других сайтах их переводы есть в Kodik плеере.

Контролируете ли вы апишку `https://kodikapi.com/search?token={token}&shikimori_id={anime id}`? Если да, то можете добавить и их озвучку в результаты поиска?

**Comment by qt-kaneko** [comment]
Нет, это официальное апи Kodik. Странно что в Shikiplayer'е нет, а на других есть. Можете предоставить ссылки посмотреть, пожалуйста?

**Comment by Lenni-s** [comment]
Извиняюсь, озвучка есть и на Шики. У них просто название английское "Studio Band"
