### ISSUE TITLE
Плеер Kodik пропала кнопка "Продолжить Просмотр"

### ISSUE THREAD

**Issue by Lenni-s** [qt-kaneko/Shikiplayer#13]
После обновления до версии 6.0.3, пропала кнопка "Продолжить Просмотр" в плеере Kodik. 
На других сайтах с Кодиком кнопка все еще работает, только в Шикиплеере пропала

**Comment by qt-kaneko** [comment]
Шикиплеер автоматически сохраняет время просмотра (и восстанавливает его) если аниме находится в списке Смотрю/Перематриваю, так что кнопка была убрана за ненадобностью.

**Comment by Lenni-s** [comment]
Сейчас плеер восстанавливает только серию на которой закончили, но видео всегда начинается с начала. 
Раньше кнопка "Продолжить Просмотр" запоминала еще и время на котором закончили просмотр
