### ISSUE TITLE
firefox - нет кнопок управления ярлыком

### ISSUE THREAD

**Issue by TristisOris** [qt-kaneko/Shikiplayer#4]
Нельзя вытащить на основную панель. Эти кнопки видимо нужно отдельно включать. ff 115

![image](https://github.com/qt-kaneko/Shikiplayer/assets/1270117/f7e4a88b-d36b-46c4-a88a-301f7bd4a3f7)

**Comment by qt-kaneko** [comment]
Расширение работает в фоне и не требует взаимодействия с пользователем (не имеет меню) из-за этого его, наверно, нельзя добавить в меню.

**Comment by TristisOris** [comment]
понял, занятное поведение.
